language: python
sudo: false
python:
  - "2.7"
# command to install dependencies
install:
  - pip install  -r requirements.txt
# command to run tests
script: nosetests

deploy:
  provider: lambda
  function_name: "$function"
  role: "$role"
  region: "eu-west-1"
  handler_name: "handle"
  module_name: "main"
  access_key_id: "$key_id"
  secret_access_key: "$secret_key"
  runtime: "python2.7"
  description: "SQS access : {context.env['TRAVIS_BUILD_NUMBER']} to AWS Lambda via Travis CI"
